schema: 'src/lib/graphql/schema.graphql'
documents: ['**/*.graphql']
extensions:
    endpoints:
        default:
            url: 'http://localhost:1337/v1/graphql'
            headers:
                'X-Hasura-Admin-Secret': 'nhost-admin-secret'
