export const resume = {
	basics: {
		name: 'Gregory Forel',
		label: '',
		email: 'gregory.forel@gmail.com',
		phone: '+34 644 40 21 47',
		url: '',
		summary: '',
		location: {
			address: 'Carrer de la Marina 56 apt 2-1',
			postalCode: '08005',
			city: 'Barcelona',
			countryCode: 'Spain',
			region: 'Barcelona',
		},
	},
	work: [
		{
			position: 'Global Program Manager',
			name: 'Microsoft',
			url: 'https://microsoft.com',
			startDate: '2014-03-01',
			endDate: 'Present',
			location: 'EMEA - remote',
			summary: 'Worldwide Inside Sales & Analytics',
			highlights: [
				'Marketing automation',
				'Dynamics CRM Online & AX (ERP)',
				'Customer Success',
				'Demand Generation Full-Cycle Sales outsourcing',
				'Led onboarding of 10 countries while coordinating Subsidiaries, Microsoft Partners and Service Providers.',
				'Outsourced Sales execution ',
				'Developed PowerBI data model and dashboard used by 30+ executives, accounting for multi-billion US$ in sales.',
			],
		},
		{
			position: 'Group IT Program Manager',
			name: 'OCS One Complete Solution',
			url: 'https://www.ocs.com/',
			startDate: '2012-01-01',
			endDate: '2014-02-01',
			location: 'Dublin, Ireland',
			summary: 'ERP & CRM implementations',
			highlights: [
				'Implemented SAGE CRM.',
				'Led development of new ERP for new business.',
				'Streamlined processes.',
				'And many more improvements.',
			],
		},
		{
			position: 'Program Manager',
			name: 'Kerry Group',
			url: 'https://www.kerrygroup.com/',
			startDate: '2009-02-01',
			endDate: '2012-01-01',
			location: 'Dublin, Ireland',
			summary: 'ERP Migration',
			highlights: ['Too much work', 'Streamlined processes.', 'And many more improvements.'],
		},
		{
			position: 'Digital Transformation Manager',
			name: 'Impsa',
			url: 'https://www.impsa.com/',
			startDate: '2005-08-01',
			endDate: '2009-02-01',
			location: 'Mendoza, Argentina',
			summary: 'Engineering',
			highlights: [
				'Led team of 30 engineers to replace 2D CAD with SolidEdge and TeamCenter.',
				'Established new workflow and trained 120 staff in Engineering Department and ensured smooth change management.',
			],
		},
	],
	volunteer: [],
	education: [
		{
			institution: 'UNCuyo, Universidad Nacional de Cuyo',
			url: 'https://www.uncuyo.edu.ar/',
			area: 'Logistics',
			location: 'Mendoza, Argentina',
			studyType: 'Master in',
			startDate: '2005-07-01',
			endDate: '2007-05-01',
			score: null,
			courses: [],
		},
		{
			institution: 'ENIM, École Nationale des Ingénieurs de Metz',
			url: 'https://institution.com/',
			area: 'Mechanical Engineering',
			location: 'Metz, France',
			studyType: 'Master in',
			startDate: '2000-09-01',
			endDate: '2005-06-30',
			score: null,
			courses: [],
		},
	],
	awards: [],
	certificates: [
		{
			name: 'PMP',
			date: '2011-08-22',
			issuer: 'PMI',
			url: 'https://pmi.org/',
		},
		{
			name: 'CSM - Certified Scrum Master',
			date: '2013-08-01',
			issuer: 'Scrum Alliance',
			url: 'https://scrumalliance.org/',
		},
		{
			name: 'PSM - Professional Scrum Master',
			date: '2013-08-01',
			issuer: 'Scrum',
			url: 'https://scrum.org/',
		},
		{
			name: 'MSP - Program Management',
			date: '2013-08-22',
			issuer: 'APMG-PRINCE2',
			url: null,
		},
	],
	publications: [],
	skills: [
		{
			name: null,
			keywords: ['Leadership', 'Program & Project Management', 'Business Intelligence'],
		},
		{
			name: 'Web Development',
			keywords: [
				'HTML',
				'CSS',
				'JavaScript',
				'Typescript',
				'React',
				'Svelte',
				'NextJS',
				'GraphQL',
				'NodeJs',
				'Git',
			],
		},
		{
			name: 'BI',
			keywords: ['SQL', 'PowerBI', 'DAX', 'Excel', 'Data Model', 'ETL'],
		},
	],
	languages: [
		{
			language: 'English',
			fluency: 'Bilingual Proficiency',
		},
		{
			language: 'French',
			fluency: 'Native speaker',
		},
		{
			language: 'Spanish',
			fluency: 'Bilingual Proficiency',
		},
	],
	interests: [
		{
			name: 'Wildlife',
			keywords: ['Ferrets', 'Unicorns'],
		},
	],
	references: [],
	projects: [],
}
